defaults:
  - base

name: das
# Update this path if necessary to the output_dir you chose.
path: ./data/das_dataset/
ev_repr_name: 'stacked_histogram_dt=50_nbins=10'
# sequence_length defines how many historical representation bins the SNN uses.
# Each bin is 50ms, so 100 bins = 5 seconds.
sequence_length: 100
# Input resolution must be multiples of 32 for YOLO backbones.
# We pad your 250 (time) x 50 (channels) to 256 x 64 in the generation script.
resolution_hw: [256, 64]
downsample_by_factor_2: False
# Our dataset only contains labels for the end of the window.
only_load_end_labels: True
