defaults:
  - base

name: gen1
path: ./data/st_yolo_das/
ev_repr_name: 'stacked_histogram_dt=200_nbins=10'
sequence_length: 20
resolution_hw: [400, 50]
downsample_by_factor_2: False
only_load_end_labels: True